### ISSUE TITLE
All Samples are -1

### ISSUE THREAD

**Issue by Saschko2000** [atomic14/esp32-i2s-mic-test#1]
When I run the Code, all I see an the Serial Port are lots of -1 :-(

The Code Works with the INMP441-Breakoutboard, but not with the ICS-43434.

Have you any idea, on how to test the mic step by step?

Thank you very much

   Sascha

**Comment by cgreening** [comment]
Make sure you are connecting the L/R pin to GND to ensure the microphone is on the left chanel.

**Comment by Saschko2000** [comment]
My be a problem with the board an the soldering, but i double-checked everything. I mesured the pcb and soldered a second board with the same result :-(. I hope this is a software problem, an not a hardware one. To check this, I just ordered one of your board, But now I have to wait for delivery ;-)

Have you any idea, I could test meanwile?

Thanks a lot
    Sascha

**Comment by cgreening** [comment]
Good news and bad news I guess - good news that it's not one of my boards! Bad news that your boards are not working. I just put your order in the post so you should receive it in 3-5 days (though with Covid and Brexit, delivery times are wildly optimistic).

If the INMP is working then it's probably not a software problem. Can you share the boards you are using and the wiring you have used?

**Comment by Saschko2000** [comment]
[ESP32 WLED Schematic.pdf](https://github.com/atomic14/esp32-i2s-mic-test/files/6694322/ESP32.WLED.Schematic.pdf)
![ESP32 WLED Board](https://user-images.githubusercontent.com/10995400/122927831-8c12c800-d369-11eb-8fe3-b1aec7346b86.png)

**Comment by Saschko2000** [comment]
And thanks a lot for fast replay and sending. :-)

**Comment by cgreening** [comment]
Looking at the schematic - the pins are wired up as:

WS - IO15
SCK - IO14
SD - IO32

Probably a silly question, but have you change the code to match?

```c++
#define I2S_MIC_SERIAL_CLOCK GPIO_NUM_14
#define I2S_MIC_LEFT_RIGHT_CLOCK GPIO_NUM_15
#define I2S_MIC_SERIAL_DATA GPIO_NUM_32
```

**Comment by cgreening** [comment]
Just having a look at the PCB layout. I might be missing it, but I think the GND of the ICS-43434 is not connected to anything? And I can't find C4 anywhere.

![Screenshot 2021-06-22 at 15 12 00](https://user-images.githubusercontent.com/706944/122940707-9e423580-d36c-11eb-94bb-885c2ce52be2.png)

**Comment by Saschko2000** [comment]
Yes, this just looks like, but is only for better visualisation. In real, the top and the bottom layer have a ground-plane.

> Probably a silly question, but have you change the code to match?

Yes and No. I did change the code, but I made a fucking mistake. Despite double-checking everything.
I hate this.
You are my Hero for today. Now I get values :-)

Thank you :-)

**Comment by cgreening** [comment]
That's great news! Looks like an interesting project. Good luck with it.

**Comment by Aishwarya876** [comment]
> When I run the Code, all I see an the Serial Port are lots of -1 :-(
> 
> The Code Works with the INMP441-Breakoutboard, but not with the ICS-43434.
> 
> Have you any idea, on how to test the mic step by step?
> 
> Thank you very much
> 
> Sascha
Even im getting same error i would be very greatful if anyone could help me (on serial monitor its just -1)

**Comment by Saschko2000** [comment]
Please let us know your code, and how you connected the mic.
In my case it was an error in my code.

**Comment by Aishwarya19966** [comment]
connections:

VDD | 3v3 |
GND | GND | GND
L/R | GND | Left channel or right channel
WS | 22 | Left right clock
SCK | 26 | Serial clock
SD | 21 | Serial data

[Here is the code link ](https://github.com/atomic14/esp32-i2s-mic-test/blob/main/i2s_mic_test/i2s_mic_test.ino)
![WhatsApp Image 2022-01-23 at 12 07 01](https://user-images.githubusercontent.com/60593880/150667721-19ccdad5-17be-415a-b155-255058e39e60.jpeg)
![Screenshot 2022-01-23 at 12 13 40 PM](https://user-images.githubusercontent.com/60593880/150667776-aaaaec51-cd0e-4453-beac-29a7be5be8cb.png)

I would be very greatful for any help

**Comment by Saschko2000** [comment]
But you changed the pin configuration from

```
#define I2S_MIC_SERIAL_CLOCK GPIO_NUM_32
#define I2S_MIC_LEFT_RIGHT_CLOCK GPIO_NUM_25
#define I2S_MIC_SERIAL_DATA GPIO_NUM_33
```

to

```
#define I2S_MIC_SERIAL_CLOCK GPIO_NUM_26
#define I2S_MIC_LEFT_RIGHT_CLOCK GPIO_NUM_22
#define I2S_MIC_SERIAL_DATA GPIO_NUM_21
```

right?

**Comment by Aishwarya19966** [comment]
Yes I Did change pins in code as well

**Comment by Aishwarya19966** [comment]
Yes I Did change pins in code as well

**Comment by Aishwarya19966** [comment]
Hey can you please help me with your email ID i have been trying on this. since too long its not working i really need help
